### PR TITLE
Fix for ALL_UPPERCASE names

### PR DESCRIPTION
**Pull request by Hypnootika**

### CODE REVIEW

**Comment by qb-0** [comment]
If I'm not wrong, this will force all module names to be lower case. Is that always the case in windows?

**Comment by NyshMy** [comment]
so? nimpy.Exception: Unexpected error encountered: Module 'DNF.exe' not found 

What is the root cause of this problem？

**Comment by qb-0** [comment]
I guess the correct fix for https://github.com/qb-0/pyMeow/blob/master/src/memcore.nim#L222 would be enumModules.toSeq[0] then. This needs to be tested on linux also.

Im not on machine till monday. So we either do it with the pr or I'll change it monday.

**Comment by NyshMy** [comment]
I pulled the latest code and compiled it, but it still doesn't seem to work. Is it caused by a change in some part of the code? It was able to open normally in last year's version

**Comment by qb-0** [comment]
Thanks Frog

**Pull request merged**
